//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatDetail
    {
        public long MessageID { get; set; }
        public long ChatID { get; set; }
        public System.DateTime MessageDate { get; set; }
        public long MessageFrom { get; set; }
        public long MessageTo { get; set; }
        public bool IsRead { get; set; }
    
        public virtual ChatMaster ChatMaster { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
