//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMaster
    {
        public ChatMaster()
        {
            this.ChatDetails = new HashSet<ChatDetail>();
        }
    
        public long ChatID { get; set; }
        public System.DateTime ChatDate { get; set; }
        public string ChatFMessage { get; set; }
        public long FromUser { get; set; }
        public long ToUser { get; set; }
        public bool IsRead { get; set; }
    
        public virtual ICollection<ChatDetail> ChatDetails { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
